version: '3'
services:

  #PHP Service
  php_fpm_app:
    volumes:
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  node_app:
    command: npm run watch

  #Nginx Service
  webserver:
    volumes:
      - ./nginx/conf.d/development/:/etc/nginx/conf.d/

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: mailhog
  #   restart: unless-stopped
  #   tty: true
  #   networks:
  #     - app-network
