// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR'
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS'
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// flash.js
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'

// users.js
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS'
export const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE'

// profile.js
export const IS_USER_AUTH = 'IS_USER_AUTH'
export const FETCH_PROFILE_USER_SUCCESS = 'FETCH_PROFILE_USER_SUCCESS'
